#!/usr/bin/python
# -*- coding: utf-8 -*-

from __future__ import division
import sys
from pylab import *
from scipy import *
import math

def usage():
    print "USAGE : ./108monstre a (a >= 2) nmax (int)"
    sys.exit()

def frange(start, stop, step):
    i = start
    while i < stop:
        yield i
        i += step

def calc_x(a, kmax, x):
    k = 0
    n = 0
    while (k <= kmax):
        try:
            n += cos(a**k * pi * x) / 2**k
        except OverflowError:
            print "Overflow reached, prog is quitting"
            sys.exit(1)
        k += 1
    return n

def launch(a, kmax):
    x = []
    y = []
    for i in frange(-2, 2, 0.001):
        y.append(calc_x(a, kmax, i))
        x.append(i)
    plot(x, y, 'g')

if (len(sys.argv) != 3):
    usage()
elif (len(sys.argv) == 3):
    try:
        a = float(sys.argv[1])
    except:
        print "Please enter a number"
        usage()
    if (a < 2):
        print "ERROR : a < 2"
        usage()
    try:
        nmax = int(sys.argv[2])
    except:
        print "Please enter a number"
        usage()
    launch(float(a), int(nmax))

fig = gcf()
fig.canvas.set_window_title('RELEASE THE KRAKEN')
title("a = " + str(a) + " ; nmax = " + str(nmax), fontsize=16)
show()
